In [2]:
import pandas as pd

In [3]:
event = pd.read_csv("event codes.txt", sep='\t')
gamelineup= pd.read_csv("Game Lineup Data.txt", sep='\t')
playbyplay= pd.read_csv("Play by Play Data Sample.txt", sep='\t')

In [5]:
event.head()

,Event_Msg_Type,Action_Type,Event_Msg_Type_Description,Action_Type_Description
0,1,0,Made Shot,No Shot
1,1,1,Made Shot,Jump Shot
2,1,3,Made Shot,Hook Shot
3,1,4,Made Shot,Tip Shot
4,1,5,Made Shot,Layup Shot

In [17]:
event["Event_Msg_Type_Description"].unique()

array(['Made Shot                               ',
       'Missed Shot                             ',
       'Free Throw                              ',
       'Rebound                                 ',
       'Turnover                                ',
       'Foul                                    ',
       'Violation                               ',
       'Substitution                            ',
       'Timeout                                 ',
       'Jump Ball                               ',
       'Ejection                                ',
       'Start Period                            ',
       'End Period                              ',
       'No Shot                                 '], dtype=object)

In [18]:
gamelineup.head(30)

,Game_id,Period,Person_id,Team_id,status
0,021fd159b55773fba8157e2090fe0fe2,1,881f83d2dee3f18c7d1751659406144e,012059d397c0b7e5a30a5bb89c0b075e,A
1,021fd159b55773fba8157e2090fe0fe2,1,27ea17a8685c4919f157e83fe9cb2d9e,cff694c8186a4bd377de400e4f60fe47,A
2,021fd159b55773fba8157e2090fe0fe2,1,57bbd7e30bc694aeee9ee40c583e6811,cff694c8186a4bd377de400e4f60fe47,A
3,021fd159b55773fba8157e2090fe0fe2,1,cec898a1d355dbfbad8c760615fde1af,012059d397c0b7e5a30a5bb89c0b075e,A
4,021fd159b55773fba8157e2090fe0fe2,1,33963fe856a1523ff46438ba07d1d99f,cff694c8186a4bd377de400e4f60fe47,A
5,021fd159b55773fba8157e2090fe0fe2,1,a99f44bbff39e352191a870e17f04537,012059d397c0b7e5a30a5bb89c0b075e,A
6,021fd159b55773fba8157e2090fe0fe2,1,c00264c3114d23bac482e9de50fb7d28,cff694c8186a4bd377de400e4f60fe47,A
7,021fd159b55773fba8157e2090fe0fe2,1,89706b99ddd00dc05d37ef5cafc04276,012059d397c0b7e5a30a5bb89c0b075e,A
8,021fd159b55773fba8157e2090fe0fe2,1,2b313e2bcef0268bc8e9415132ba9997,012059d397c0b7e5a30a5bb89c0b075e,A
9,021fd159b55773fba8157e2090fe0fe2,1,307beab25b1021a548b4a47550bc4b25,cff694c8186a4bd377de400e4f60fe47,A
10,021fd159b55773fba8157e2090fe0fe2,2,8bb18fb1d0cc10c985afa823ecec6d18,cff694c8186a4bd377de400e4f60fe47,A
11,021fd159b55773fba8157e2090fe0fe2,2,c1fe6ed491d04e3cdf50755dff23b263,cff694c8186a4bd377de400e4f60fe47,A
12,021fd159b55773fba8157e2090fe0fe2,2,2d9594e4d250679e7a3383ad5ccd2f44,012059d397c0b7e5a30a5bb89c0b075e,A
13,021fd159b55773fba8157e2090fe0fe2,2,d6bc5eb6ed54c734628cb4d237f99031,012059d397c0b7e5a30a5bb89c0b075e,A
14,021fd159b55773fba8157e2090fe0fe2,2,603daefb2fa321f3abab289805fdcc25,cff694c8186a4bd377de400e4f60fe47,A
15,021fd159b55773fba8157e2090fe0fe2,2,33963fe856a1523ff46438ba07d1d99f,cff694c8186a4bd377de400e4f60fe47,A
16,021fd159b55773fba8157e2090fe0fe2,2,a99f44bbff39e352191a870e17f04537,012059d397c0b7e5a30a5bb89c0b075e,A
17,021fd159b55773fba8157e2090fe0fe2,2,89706b99ddd00dc05d37ef5cafc04276,012059d397c0b7e5a30a5bb89c0b075e,A
18,021fd159b55773fba8157e2090fe0fe2,2,b2fada91a0c8a0f400623c425286ae2e,012059d397c0b7e5a30a5bb89c0b075e,A
19,021fd159b55773fba8157e2090fe0fe2,2,60b5f9f68ccbbf7ba3fa13a2189e2775,cff694c8186a4bd377de400e4f60fe47,A
20,021fd159b55773fba8157e2090fe0fe2,3,881f83d2dee3f18c7d1751659406144e,012059d397c0b7e5a30a5bb89c0b075e,A
21,021fd159b55773fba8157e2090fe0fe2,3,27ea17a8685c4919f157e83fe9cb2d9e,cff694c8186a4bd377de400e4f60fe47,A
22,021fd159b55773fba8157e2090fe0fe2,3,57bbd7e30bc694aeee9ee40c583e6811,cff694c8186a4bd377de400e4f60fe47,A
23,021fd159b55773fba8157e2090fe0fe2,3,cec898a1d355dbfbad8c760615fde1af,012059d397c0b7e5a30a5bb89c0b075e,A
24,021fd159b55773fba8157e2090fe0fe2,3,33963fe856a1523ff46438ba07d1d99f,cff694c8186a4bd377de400e4f60fe47,A
25,021fd159b55773fba8157e2090fe0fe2,3,a99f44bbff39e352191a870e17f04537,012059d397c0b7e5a30a5bb89c0b075e,A
26,021fd159b55773fba8157e2090fe0fe2,3,c00264c3114d23bac482e9de50fb7d28,cff694c8186a4bd377de400e4f60fe47,A
27,021fd159b55773fba8157e2090fe0fe2,3,89706b99ddd00dc05d37ef5cafc04276,012059d397c0b7e5a30a5bb89c0b075e,A
28,021fd159b55773fba8157e2090fe0fe2,3,2b313e2bcef0268bc8e9415132ba9997,012059d397c0b7e5a30a5bb89c0b075e,A
29,021fd159b55773fba8157e2090fe0fe2,3,307beab25b1021a548b4a47550bc4b25,cff694c8186a4bd377de400e4f60fe47,A

In [16]:
len(gamelineup)

2040

In [15]:
playbyplay.head()

,Game_id,Event_Num,Event_Msg_Type,Period,WC_Time,PC_Time,Action_Type,Option1,Option2,Option3,Team_id,Person1,Person2,Team_id_type
0,021fd159b55773fba8157e2090fe0fe2,0,12,1,546427,7200,0,0,0,0,1473d70e5646a26de3c52aa1abd85b1f,6bcf6c1f8c373d25fca1579bc4464a91,6bcf6c1f8c373d25fca1579bc4464a91,0
1,021fd159b55773fba8157e2090fe0fe2,1,10,1,546495,7200,0,0,0,0,012059d397c0b7e5a30a5bb89c0b075e,89706b99ddd00dc05d37ef5cafc04276,307beab25b1021a548b4a47550bc4b25,2
2,021fd159b55773fba8157e2090fe0fe2,2,2,1,546665,7050,1,3,0,0,012059d397c0b7e5a30a5bb89c0b075e,cec898a1d355dbfbad8c760615fde1af,6bcf6c1f8c373d25fca1579bc4464a91,2
3,021fd159b55773fba8157e2090fe0fe2,3,4,1,546714,6960,0,0,0,0,012059d397c0b7e5a30a5bb89c0b075e,307beab25b1021a548b4a47550bc4b25,6bcf6c1f8c373d25fca1579bc4464a91,2
4,021fd159b55773fba8157e2090fe0fe2,6,6,1,546886,6920,4,0,0,0,cff694c8186a4bd377de400e4f60fe47,c00264c3114d23bac482e9de50fb7d28,89706b99ddd00dc05d37ef5cafc04276,3